name: keras
dependencies:
- _nb_ext_conf=0.3.0=py27_0
- anaconda-client=1.5.1=py27_0
- apptools=4.4.0=py27_0
- backports=1.0=py27_0
- backports_abc=0.4=py27_0
- cairo=1.14.8=0
- cloog=0.18.0=0
- clyent=1.2.2=py27_0
- conda-forge::funcsigs=1.0.2=py27_0
- conda-forge::libiconv=1.14=4
- conda-forge::mock=2.0.0=py27_0
- conda-forge::pbr=1.10.0=py27_0
- conda-forge::protobuf=3.0.0b2=py27_0
- conda-forge::six=1.10.0=py27_0
- conda-forge::tensorflow=0.10.0=py27_0
- configobj=5.0.6=py27_0
- configparser=3.5.0=py27_0
- cycler=0.10.0=py27_0
- dbus=1.10.10=0
- decorator=4.0.10=py27_0
- entrypoints=0.2.2=py27_0
- enum34=1.1.6=py27_0
- envisage=4.5.1=py27_0
- expat=2.1.0=0
- fontconfig=2.12.1=3
- freetype=2.5.5=2
- functools32=3.2.3.2=py27_0
- gcc=4.8.5=6
- get_terminal_size=1.0.0=py27_0
- glib=2.50.2=1
- gmp=5.1.2=2
- graphviz=2.38.0=2
- gst-plugins-base=1.8.0=0
- gstreamer=1.8.0=0
- harfbuzz=0.9.39=1
- hdf5=1.8.17=1
- icu=54.1=0
- ipykernel=4.5.0=py27_0
- ipython=5.1.0=py27_0
- ipython_genutils=0.1.0=py27_0
- ipywidgets=5.2.2=py27_0
- isl=0.12.2=0
- jbig=2.1=0
- jinja2=2.8=py27_1
- jpeg=8d=2
- jsonschema=2.5.1=py27_0
- jupyter=1.0.0=py27_3
- jupyter_client=4.4.0=py27_0
- jupyter_console=5.0.0=py27_0
- jupyter_core=4.2.0=py27_0
- libffi=3.2.1=0
- libgcc=5.2.0=0
- libgfortran=3.0.0=1
- libgpuarray=0.6.4=0
- libpng=1.6.27=0
- libsodium=1.0.10=0
- libtiff=4.0.6=2
- libtool=2.4.2=0
- libxcb=1.12=0
- libxml2=2.9.2=0
- llvmlite=0.17.0=py27_0
- mako=1.0.6=py27_0
- markupsafe=0.23=py27_2
- matplotlib=1.5.1=np111py27_0
- mistune=0.7.3=py27_0
- mkl=11.3.3=0
- mpc=1.0.1=0
- mpfr=3.1.2=0
- nb_anacondacloud=1.2.0=py27_0
- nb_conda=2.0.0=py27_0
- nb_conda_kernels=2.0.0=py27_0
- nbconvert=4.2.0=py27_0
- nbformat=4.1.0=py27_0
- nbpresent=3.0.2=py27_0
- networkx=1.11=py27_0
- nose=1.3.7=py27_1
- notebook=4.2.3=py27_0
- numba=0.32.0=np111py27_0
- numpy=1.11.1=py27_0
- opencv=3.1.0=np111py27_1
- openssl=1.0.2j=0
- pandas=0.19.2=np111py27_1
- pango=1.40.3=1
- path.py=8.2.1=py27_0
- pathlib2=2.1.0=py27_0
- pcre=8.39=1
- pexpect=4.0.1=py27_0
- pickleshare=0.7.4=py27_0
- pillow=3.4.2=py27_0
- pip=8.1.2=py27_0
- pixman=0.34.0=0
- prompt_toolkit=1.0.3=py27_0
- ptyprocess=0.5.1=py27_0
- pycairo=1.10.0=py27_0
- pydot=1.0.28=py27_0
- pyface=5.1.0=py27_0
- pygments=2.1.3=py27_0
- pygpu=0.6.4=py27_0
- pyparsing=1.5.6=py27_0
- pyqt=4.11.4=py27_4
- pyside=1.2.0=py27_0
- python=2.7.12=1
- python-dateutil=2.5.3=py27_0
- pytz=2016.6.1=py27_0
- pywavelets=0.5.2=np111py27_0
- pyyaml=3.12=py27_0
- pyzmq=15.4.0=py27_0
- qt=4.8.6=3
- qtconsole=4.2.1=py27_0
- readline=6.2=2
- requests=2.11.1=py27_0
- scikit-image=0.13.0=np111py27_0
- scikit-learn=0.18=np111py27_0
- scipy=0.18.1=np111py27_0
- seaborn=0.7.1=py27_0
- setuptools=27.2.0=py27_0
- shiboken=1.2.1=py27_0
- simplegeneric=0.8.1=py27_1
- singledispatch=3.4.0.3=py27_0
- sip=4.18=py27_0
- sqlite=3.13.0=0
- ssl_match_hostname=3.4.0.2=py27_1
- subprocess32=3.2.7=py27_0
- terminado=0.6=py27_0
- tk=8.5.18=0
- tornado=4.4.1=py27_0
- traitlets=4.3.0=py27_0
- traits=4.6.0=py27_0
- traitsui=5.1.0=py27_0
- vtk=6.3.0=py27_1
- wcwidth=0.1.7=py27_0
- wheel=0.29.0=py27_0
- widgetsnbextension=1.2.6=py27_0
- xz=5.2.2=1
- yaml=0.1.6=0
- zeromq=4.1.4=0
- zlib=1.2.8=3
- pip:
  - alabaster==0.7.9
  - anaconda-navigator==1.5
  - anaconda-project==0.4.1
  - appdirs==1.4.0
  - argcomplete==1.0.0
  - astroid==1.4.9
  - astropy==1.3
  - babel==2.3.4
  - backports-abc==0.4
  - backports.shutil-get-terminal-size==1.0.0
  - backports.ssl-match-hostname==3.4.0.2
  - beautifulsoup4==4.5.3
  - bitarray==0.8.1
  - blaze==0.10.1
  - bokeh==0.12.4
  - boto==2.40.0
  - bottleneck==1.2.0
  - cdecimal==2.3
  - cffi==1.6.0
  - chardet==2.3.0
  - chest==0.2.3
  - click==6.7
  - cloudpickle==0.2.2
  - colorama==0.3.7
  - conda==4.3.16
  - conda-build==2.1.2
  - conda-env==2.5.0a0
  - conda-verify==2.0.0
  - contextlib2==0.5.4
  - cryptography==1.7.1
  - cython==0.25.2
  - cytoolz==0.8.2
  - dask==0.13.0
  - datashape==0.5.4
  - denseinferencewrapper==1.0.0
  - dill==0.2.5
  - docutils==0.13.1
  - drmaa==0.7.6
  - dynd==0.7.3.dev1
  - et-xmlfile==1.0.1
  - fastcache==1.0.2
  - filelock==2.0.7
  - flask==0.12
  - flask-cors==3.0.2
  - funcsigs==1.0.2
  - futures==3.0.5
  - gevent==1.2.1
  - greenlet==0.4.11
  - gridmap==0.13.0
  - grin==1.2.1
  - h5py==2.6.0
  - heapdict==1.0.0
  - idna==2.2
  - imagesize==0.7.1
  - ipaddress==1.0.18
  - ipython-genutils==0.1.0
  - isort==4.2.5
  - itsdangerous==0.24
  - jdcal==1.3
  - jedi==0.9.0
  - joblib==0.11
  - jupyter-client==4.4.0
  - jupyter-console==5.0.0
  - jupyter-core==4.2.0
  - keras==2.0.3
  - keras-diagram==1.0.5
  - lazy-object-proxy==1.2.2
  - locket==0.2.0
  - lxml==3.7.2
  - mayavi==4.5.0
  - mock==2.0.0
  - mpmath==0.19
  - multipledispatch==0.4.9
  - multiprocessing==2.6.2.1
  - nb-anacondacloud==1.2.0
  - nb-conda==2.0.0
  - nb-conda-kernels==2.0.0
  - nibabel==2.1.0
  - nilearn==0.3.0
  - nltk==3.2.2
  - numexpr==2.6.1
  - numpydoc==0.6.0
  - odo==0.5.0
  - openpyxl==2.4.1
  - packaging==16.8
  - partd==0.3.7
  - patsy==0.4.1
  - pbr==1.10.0
  - pep8==1.7.0
  - pkginfo==1.4.1
  - plotly==2.0.2
  - ply==3.9
  - prompt-toolkit==1.0.3
  - protobuf==3.0.0b2
  - psutil==5.0.1
  - py==1.4.32
  - pyasn1==0.1.9
  - pycosat==0.6.1
  - pycparser==2.17
  - pycrypto==2.6.1
  - pycurl==7.43.0
  - pydot-ng==1.0.0
  - pyflakes==1.5.0
  - pylint==1.6.4
  - pyopenssl==16.2.0
  - pytest==3.0.5
  - qtawesome==0.4.3
  - qtpy==1.2.1
  - redis==2.10.5
  - rope==0.9.4
  - ruamel-yaml-==VERSION
  - scandir==1.4
  - simpleitk==1.0.0
  - six==1.10.0
  - snowballstemmer==1.2.1
  - sockjs-tornado==1.0.3
  - sphinx-rtd-theme==0.1.9
  - spyder==3.1.3
  - sqlalchemy==1.1.5
  - statsmodels==0.6.1
  - stevedore==1.21.0
  - sympy==1.0
  - tables==3.3.0
  - tensorflow==0.10.0
  - theano==0.9.0
  - toolz==0.8.2
  - tqdm==4.11.2
  - unicodecsv==0.14.1
  - virtualenv-clone==0.2.6
  - virtualenvwrapper==4.7.2
  - werkzeug==0.11.15
  - wrapt==1.10.8
  - xlrd==1.0.0
  - xlsxwriter==0.9.6
  - xlwt==1.2.0

